site_name: py_tenma_app
site_url: https://chaitu-ycr.github.io/py_tenma_app/
site_description: python ğŸ flask application for tenma power supply
site_author: chaitu-ycr

repo_name: chaitu-ycr/py_tenma_app
repo_url: https://github.com/chaitu-ycr/py_tenma_app
edit_uri: blob/main/docs/


nav:
  - Documentation: index.md

theme:
  name: material
  features:
    - toc.integrate

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true